version: '3'

services:
  database:
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gerencia
    volumes: 
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    command: yarn start:dev
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    depends_on: 
      - database
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    logging: 
      driver: none
    environment: 
      PGADMIN_DEFAULT_EMAIL: guilhermemiua@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes: 
      - ./pg-admin:/pgadmin/storage/
    depends_on: 
      - database